---
parameters:
  controller.resolver.class: 'Easy\HttpKernel\Controller\ControllerResolver'

services:

  request:
    synthetic: true

  kernel:
    synthetic: true

  service_container:
    synthetic: true

  event_dispatcher:
    class: 'Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher'
    arguments:
      - '@service_container'

  controller.resolver:
    class: '%controller.resolver.class%'
    arguments:
      - '@logger'

  http_kernel:
    class: 'Easy\HttpKernel\HttpKernel'
    arguments:
      - '@event_dispatcher'
      - '@kernel'
      - '@controller.resolver'

  RequestHandler:
    class: 'Easy\Mvc\Controller\Component\RequestHandler'

  Serializer:
    class: 'Easy\Mvc\Controller\Component\Serializer'
...