---
parameters:
  controller.resolver.class: 'Easy\Mvc\Controller\ControllerResolver'
  controller.nameparser.class: 'Easy\Mvc\Controller\ControllerNameParser'
  controller.object.nameparser.class: 'Easy\Mvc\Controller\ControllerObjectNameParser'
  event.dispatcher.class: 'Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher'
  http.kernel.class: 'Easy\HttpKernel\HttpKernel'
  file_locator.class: 'Easy\HttpKernel\Config\FileLocator'
  bundle_guesser.class: 'Easy\HttpKernel\Bundle\BundleGuesser'
  inflector.class: 'Easy\Utility\Inflector'
  
services:

  request:
    synthetic: true
    synchronized: true

  kernel:
    synthetic: true
    synchronized: true

  service_container:
    synthetic: true
    synchronized: true

  event_dispatcher:
    class: '%event.dispatcher.class%'
    arguments:
      - '@service_container'

  controller.resolver:
    class: '%controller.resolver.class%'
    arguments:
      - '@service_container'
      - '@logger'
      
  controller.nameparser:
    class: '%controller.nameparser.class%'
    arguments:
      - '@kernel'
      
  controller.object.nameparser:
    class: '%controller.object.nameparser.class%'
    arguments:
      - '@controller'
      
  http_kernel:
    class: '%http.kernel.class%'
    arguments:
      - '@event_dispatcher'
      - '@kernel'
      - '@controller.resolver'
      
  bundle_guesser:
    class: '%bundle_guesser.class%'
    arguments:
      - '@kernel'
      - '@request'
      
  file_locator:
    class: %file_locator.class%
    arguments:
      - '@kernel'
      - '%kernel.root_dir%/Resources'
      
  inflector:
    class: %inflector.class%
...