---
parameters:
  template.parser.class: 'Easy\Mvc\View\TemplateNameParser'
  helper.url.class: 'Easy\Mvc\View\Helper\UrlHelper'
  helper.session.class: 'Easy\Mvc\View\Helper\SessionHelper'
  helper.html.class: 'Easy\Mvc\View\Helper\HtmlHelper'
  helper.form.class: 'Easy\Mvc\View\Helper\FormHelper'
  template.guesser.class: 'Easy\Mvc\View\TemplateGuesser'
  
services: 
    
  template.parser:
    class: '%template.parser.class%'
    arguments: 
      - '@kernel'
      
  framework.template.guesser:
    class: '%template.guesser.class%'
    arguments:
      - '@kernel'
      
  helper.url:
    class: '%helper.url.class%'
    arguments:
      - '@router'
    tags:
      - { name: templating.helper }
     
  helper.session:
    class: '%helper.session.class%'
    tags:
      - { name: templating.helper }
      
  helper.html:
    class: '%helper.html.class%'
    arguments:
      - "@helper.url"
    tags:
      - { name: templating.helper }
      
  helper.form:
    class: '%helper.form.class%'
    arguments:
      - "@session"
      - "@helper.html"
    tags:
      - { name: templating.helper }
...