---

parameters:
  locale.class: 'Easy\Mvc\Controller\Component\Locale'
  cookie.class: 'Easy\Mvc\Controller\Component\Cookie'
  controller.metadata.class: 'Easy\Mvc\Controller\Metadata\ControllerMetadata'
  url.generator.class: 'Easy\Mvc\Routing\Generator\UrlGenerator'
  annotaion.reader.class: 'Doctrine\Common\Annotations\AnnotationReader'
  
services: 
  annotation.reader:
    class: '%annotaion.reader.class%'
    
  controller:
    synthetic: true
  
  controller.metadata:
    class: '%controller.metadata.class%'
    arguments:
      - '@controller'
      - '@annotation.reader'
    
  locale:
    class: "%locale.class%"
    
  cookie:
    class: "%cookie.class%"
    
  RequestHandler:
    class: 'Easy\Mvc\Controller\Component\RequestHandler'
    arguments:
      - '@request'
      
  serializer:
    class: 'Easy\Mvc\Controller\Component\Serializer'
    
  url:
    class: '%url.generator.class%'
    arguments:
      - '@request'
      - '@controller.nameparser'
...