language: php

php:
  - "5.4"
  - "5.3"
  - "5.2"
  
script:
 - php echo true
 
notifications:
  email:
  recipients:
    - italolelis@lellysinformatica.com
  on_success: never
  on_failure: change
   