language: php

php:
  - "5.4"
  - "5.3"
  
branches:
  only:
    - 2.0
    
before_install:
  - composer update
  
script:
 - php ./tests/run-tests.php
 
notifications:
email:
  - italolelis@lellysinformatica.com