---
parameters:
  factory.class: 'Knp\Menu\MenuFactory'
  matcher.class: 'Knp\Menu\Matcher\Matcher'
  renderer.class: 'Knp\Menu\Renderer\ListRenderer'
  voter.class: 'Knp\Menu\Matcher\Voter\UriVoter'
  
services:
  menu.factory:
    class: "%factory.class%"
    
  menu.voter:
    class: "%voter.class%"
    arguments:
      - '%server.requestUri%'
    
  menu.matcher:
    class: "%matcher.class%"
    calls:
      - ['addVoter', ['@menu.voter']]
      
  menu.renderer:
    class: "%renderer.class%"
    arguments:
      - '@menu.matcher'
...