---
Cache:
  enable: true
  
  engine: &ENGINE
    <?php echo extension_loaded('apc') ? 'APC' : 'File'; echo "\n"; ?>
    
  duration: &DURATION
    <?php echo Easy\Core\App::isDebug()? '+10 seconds' : '+999 days'; echo "\n"; ?>
    
  options:
    default:
      engine: *ENGINE
      duration: *DURATION
      probability: 100
      path: <?php echo CACHE . "\n";?>
      prefix: 'demo_easy_'
      lock: false
      serialize: true
      
    short:
      engine: *ENGINE
      duration: '+24 hours'
      probability: 100
      path: <?php echo CACHE . "\n";?>
      prefix: 'sistema_easy_'
      lock: false
      serialize: true  
        
    long:
      engine: *ENGINE
      duration: '+999 days'
      probability: 100
      path: <?php echo CACHE . "\n";?>
      prefix: 'demo_easy_'
      lock: false
      serialize: true   
      
    _easy_model_:
      engine: *ENGINE
      duration: *DURATION
      probability: 100
      path: <?php echo CACHE . 'models' . DS . "\n"; ?>
      prefix: 'demo_easy_model_'
      serialize: true
      
    _easy_core_:
      engine: *ENGINE
      duration: *DURATION
      probability: 100
      path: <?php echo CACHE . 'persistent' . DS . "\n"; ?>
      prefix: 'demo_easy_core_'
      serialize: true  
...