#
# Routes configuration
#
# In this file, you set up routes to your controllers and their actions.
# Routes are very important mechanism that allows you to freely connect
# different urls to chosen controllers and their actions (functions).
---
View:
  layouts:
    layout: Layout.tpl
    
  elements:


Routes:
  connect:
    # Here, we are connecting '/' (base path) to controller called 'Home', its action called 'index'
    '/': {controller: Home, action: index}
      
  # Here we set the Controllers that will use REST system
  mapResources:
    - Exemple
...